### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by lxvm** [macd/BaryRational.jl#10]
@macd I was wondering if a new patch or minor release could be made to include some of the latest fixes? Thank you in advance for your help.

**Comment by macd** [comment]
@lxvm Yes, that is something I should do. Here goes...
@JuliaRegistrator register()

**Comment by macd** [comment]
Forgot to add compat entry for GenericSchur. So here goes again:
@JuliaRegistrator register()

**Comment by macd** [comment]
No worries @lxvm ! Thank you for your interest and your contributions.
