### ISSUE TITLE
aaa derivative returns NaN

### ISSUE THREAD

**Issue by lxvm** [macd/BaryRational.jl#2]
Hi, I've been testing `aaa` for an application and found that `deriv(a)` can return `NaN`s for simple arguments

```julia
julia> using BaryRational

julia> F,Z = (ComplexF64[-2.0 - 0.0im, -9.007199254740992e15 - 0.0im, 1.0000000000000002 - 0.0im, 0.6666666666666666 - 0.0im, 0.9999999999999996 - 0.0im, -9.007199254740992e15 - 0.0im], ComplexF64[1.0 + 0.0im, 0.5000000000000001 + 0.8660254037844386im, -0.4999999999999998 + 0.8660254037844387im, -1.0 + 1.2246467991473532e-16im, -0.5000000000000004 - 0.8660254037844385im, 0.49999999999999933 - 0.866025403784439im])
(ComplexF64[-2.0 - 0.0im, -9.007199254740992e15 - 0.0im, 1.0000000000000002 - 0.0im, 0.6666666666666666 - 0.0im, 0.9999999999999996 - 0.0im, -9.007199254740992e15 - 0.0im], ComplexF64[1.0 + 0.0im, 0.5000000000000001 + 0.8660254037844386im, -0.4999999999999998 + 0.8660254037844387im, -1.0 + 1.2246467991473532e-16im, -0.5000000000000004 - 0.8660254037844385im, 0.49999999999999933 - 0.866025403784439im])

julia> a = aaa(Z, F ./ (im .* Z); clean=false)
(::BaryRational.AAAapprox{Vector{ComplexF64}}) (generic function with 1 method)

julia> differ(a)(1.0)
NaN + NaN*im

julia> count(isnan.(differ(a).(rand(ComplexF64, 1000)))) # show it is a problem for generic inputs
1000
```

I'm not entirely sure if this is related to the following error message, but I thought I should report the problem

```julia
julia> a = aaa(Z, F ./ (im .* Z); clean=true)
5 Froissart doublets. Number of residues = 5
cleanup: (1,)  (1,)  (6,)
(::BaryRational.AAAapprox{Vector{ComplexF64}}) (generic function with 1 method)

julia> differ(a)(1.0)
ERROR: DimensionMismatch: second dimension of A, 1, does not match length of x, 6
Stacktrace:
 [1] gemv!(y::Vector{ComplexF64}, tA::Char, A::Matrix{ComplexF64}, x::Vector{ComplexF64}, α::Bool, β::Bool)
   @ LinearAlgebra /local/opt/julia-1.8.5/share/julia/stdlib/v1.8/LinearAlgebra/src/matmul.jl:493
 [2] mul!
   @ /local/opt/julia-1.8.5/share/julia/stdlib/v1.8/LinearAlgebra/src/matmul.jl:65 [inlined]
 [3] mul!
   @ /local/opt/julia-1.8.5/share/julia/stdlib/v1.8/LinearAlgebra/src/matmul.jl:276 [inlined]
 [4] *
   @ /local/opt/julia-1.8.5/share/julia/stdlib/v1.8/LinearAlgebra/src/matmul.jl:56 [inlined]
 [5] reval(zz::Float64, z::Vector{ComplexF64}, f::Vector{ComplexF64}, w::Vector{ComplexF64})
   @ BaryRational ~/.julia/packages/BaryRational/iBBsd/src/aaa.jl:126
 [6] (::BaryRational.AAAapprox{Vector{ComplexF64}})(zz::Float64)
   @ BaryRational ~/.julia/packages/BaryRational/iBBsd/src/aaa.jl:12
 [7] top-level scope
   @ REPL[56]:1
```

**Comment by macd** [comment]
Thanks for reporting the issue. I do want to point out that the README.md says "NOTE: Currently, the derivatives are not working." (which I have just removed). I should not have left that code live, but I had intended to return to it and never had the chance to do so. Unfortunately, I don't think I will be able to look at this anytime soon. So I will remove this non working code. (But this did show me a bug in cleanup! which has been fixed)

If you need the derivatives, and do not mind the dependency, you can use BaryRational to move your function into ApproxFun. Once there, ApproxFun has many capabilities, including taking derivatives of the "Funs". There is an example on how to do this in the README.md.

**Comment by macd** [comment]
Thanks! So this gave me the motivation to take a look at this now and I have something that looks like it works (needs more testing). In the meantime, I did find another bug in the code, and I will merge the fix later today.

**Comment by macd** [comment]
Just updated repo with derivatives. They can be calculated by something like deriv.(fa, [1.2, 1.3, 9.3]) where fa is a aaa approximation.

**Comment by macd** [comment]
Cool!  I agree on your robustness observation. I'm glad you found it useful.
